### ISSUE TITLE
学习并试用Monkeyrunner

### ISSUE THREAD

**Issue by buaanostop** [buaanostop/Autotest#11]

**Comment by bhlt1998** [comment]
20190401 
>issue11 学习并使用 MonkeyRunner
##1.配置MonkeyRunner环境
分别安装配置了JDK, Android SDK, Python,就可以使用monkeyrunner了
参考链接：[monkeyrunner环境搭建及实例(三)](https://www.cnblogs.com/lynn-li/p/5885001.html)

##2.使用MonkeyRunner
通过查阅相关资料，学习了monkeyrunner的一些基本操作，并连接手机进行了测试!
![手机连接图](https://wx2.sinaimg.cn/mw690/007asqJ1ly1g1n96wdt7oj33402c0e82.jpg)
通过monkeyrunner在手机上进行了一些操作：
+ 安装app
+ 滑动屏幕
+ 点击屏幕
+ 键盘输入
+ 屏幕唤醒及解锁
+ 截图
![安装app](https://wx4.sinaimg.cn/mw690/007asqJ1gy1g1n94wsen3j30u01hc4qq.jpg)
![键盘输入](
https://wx2.sinaimg.cn/mw690/007asqJ1gy1g1n94w8faoj30u01hc3zj.jpg)
![部分代码](
https://wx2.sinaimg.cn/mw1024/007asqJ1gy1g1n94izd0ij30r70e8gnw.jpg)
图片显示不了可以去博客园看
[博客链接](https://www.cnblogs.com/bhlt1998/p/10637673.html)

**Comment by bhlt1998** [comment]
#【软件工程】团队作业日记02
20190402
##0.任务
issue 11 尝试使用Monkeyrunner 连接安卓模拟器并进行操作。

##1.选择模拟器
昨天我进行了Monkeyrunner连接真机的操作，同组的同学进行了Monkeyrunner连接模拟器的尝试，出了一些问题，他是使用Android emulator 启动模拟器，于是PM安排我今天尝试连接一下模拟器的操作。
通过一番查阅，网上普遍说自带的安卓模拟器速度慢，经常出现卡机的现象，无法连接wifi，不能用测试环境版本去进行monkeyrunner脚本测试等等问题。于是决定选择一款比较成熟的模拟器。
几经挑选之后选择了这款[夜神模拟器](http://www.yeshen.com/)

##2.模拟器安装
通过官网下载，按照提示进行安装即可，打开后在设置中设置成手机版即可。
![模拟器安装成功](https://img2018.cnblogs.com/blog/1346585/201904/1346585-20190402163053044-324296330.jpg)

##3.连接模拟器
在cmd中输入`adb devices`，发现并没有连接成功
![连接失败](https://img2018.cnblogs.com/blog/1346585/201904/1346585-20190402163137902-211771928.jpg)
解决方法：输入命令`adb connect 127.0.0.1:62001`即可，再次输入`adb devices`发现已经连接上模拟器。
![连接成功](https://img2018.cnblogs.com/blog/1346585/201904/1346585-20190402163321940-598386703.jpg)

##4.测试简单操作
###（1）键盘输入
![键盘输入](https://img2018.cnblogs.com/blog/1346585/201904/1346585-20190402163414478-739725583.jpg)
###（2）安装app
python代码
```
from com.android.monkeyrunner import MonkeyRunner,MonkeyDevice
device=MonkeyRunner.waitForConnection()
if not device:
    print("Please connect a device to start!")
else:
    print("install package test start!")
device.installPackage("E:/dontstop/com.smartisan.notes_35.apk")
print("finish")
```
![命令行执行python脚本](https://img2018.cnblogs.com/blog/1346585/201904/1346585-20190402163635588-1547441043.jpg)
![软件安装成功](https://img2018.cnblogs.com/blog/1346585/201904/1346585-20190402163711375-11313512.jpg)

但是在安装准备另一个app的时候，即使模拟器端显示安装成功，cmd还是卡着的，没有发现问题出在哪里。
![cmd卡着](https://img2018.cnblogs.com/blog/1346585/201904/1346585-20190402163839086-1260864873.jpg)
![浮光安装成功](https://img2018.cnblogs.com/blog/1346585/201904/1346585-20190402163852977-1244393037.jpg)

###（3）还进行了一下其他的基础操作
+ 点击屏幕
+ 滑动屏幕
+ 截屏

##5.使用Hierarchy Viewer
在使用Monkeyrunner编写脚本时，往往需要知道控件的坐标或者控件的ID,可以通过Hierarchy Viewer来获取控件的坐标和ID。
在Android SDK 的 tools 目录下打开 monitor.bat 启动 Android Device Monitor,
查看连接的模拟器，使用Hierarchy Viewer, 如图所示，可以获取控件的具体信息。
![android device monitor](https://img2018.cnblogs.com/blog/1346585/201904/1346585-20190402164505645-1601317994.jpg)

参考链接：
[monkeyrunner之夜神模拟器的安装与使用](https://www.cnblogs.com/lynn-li/p/5884651.html)

博客园链接
[团队作业日记02](https://www.cnblogs.com/bhlt1998/p/10643640.html)
