### ISSUE TITLE
寻找方法捕获异常

### ISSUE THREAD

**Issue by buaanostop** [buaanostop/Autotest#17]

**Comment by SiMrua** [comment]
目前版本采用的捕获异常的方法是直接比对若干张连续时间采集的图片的相似程度，如果他们相似程度极高，则判断他们为一组异常的图片。这里计算相似程度的方法是计算图片之间的欧式距离，优点是简单明了的能够发现哪些图片在整体上是极其相似的，缺点是不能捕捉关键元素是否有异常，具体讲就是有时候的异常可能是游戏角色的异常，但是游戏背景一直在更替，这时应该忽略掉游戏背景的不同而发掘游戏角色的异常行为----连续若干帧不发生变化。但是这样的难度太大了，因为不同的游戏想要确定哪部分图像为游戏角色，那部分图像为游戏背景是十分困难的，但是全面计算不同帧之间的差异是会漏掉这些特殊的异常状况的，这个问题或许会在查阅后续资料后得到解决的办法。
