### ISSUE TITLE
提供最初指定的游戏

### ISSUE THREAD

**Issue by buaanostop** [buaanostop/Autotest#37]

**Comment by SiMrua** [comment]
![image](https://user-images.githubusercontent.com/39360699/55308541-9c3ee400-548d-11e9-90cf-52a55b036b7c.png)
七天有效，赶快下载~

**Comment by SiMrua** [comment]
https://pan.baidu.com/s/1QCLTaswO0PKRwefa1x_3Yg

提取码：6zkg
