### ISSUE TITLE
完善后端接口定义

### ISSUE THREAD

**Issue by buaanostop** [buaanostop/Autotest#40]

**Comment by SiMrua** [comment]
1.picture_classification(picture_collection_path)
•用来进行图片分类的函数
•picture_collection_path : 图片集的存储路径
•return : 返回一个分类后索引的集合，index_collection

2.train_module(picture_collection_path, index_collection)
•用来训练的模块，未定使用什么模型来训练
•picture_collection_path : 图片集的存储路径，index_collection : 分类后索引的集合
•return : 返回一个或多个用来调节模型的参数，这里还没确定要用的模型所以不确定返回多少个参数，也有可能会分多个函数去实现它

3.prediction_module(real_time_pictures)
•用来检测游戏是否发生异常的模块，模型里的参数为训练模块中得到的参数，通过不断地监测一组组连续的图片来检测游戏是否发生了异常
• real_time_pictures : 实时的一组图像，大概会是十张连续时刻的图像为一组或者更多
•return : True or False，来表明此组图片异常与否
