### ISSUE TITLE
测试序列保存、载入、添加、删除

### ISSUE THREAD

**Issue by buaanostop** [buaanostop/Autotest#55]
保存：将当前设定的测试序列作为存档供以后直接调用
载入：清空当前序列并载入已保存的测试序列
添加：保留当前序列并将载入内容添加至末尾
删除：删除保存的序列

**Comment by bhlt1998** [comment]
https://github.com/buaanostop/Autotest/tree/d21842b1433922f6b90443c65f69758912deb17f
