### ISSUE TITLE
搜寻合适的模型

### ISSUE THREAD

**Issue by buaanostop** [buaanostop/Autotest#8]

**Comment by SiMrua** [comment]
我认为我们最终要解决的问题，是一个异常检测的问题，所以可以参考这篇常用的异常检测方法的博客：https://www.cnblogs.com/pinard/p/9314198.html
其中提到的Isolation Forest（孤立森林）如下：
https://blog.csdn.net/qq_39303465/article/details/79219415
https://blog.csdn.net/u013709270/article/details/73436588
iForest适用于连续数据的模型，是一种无监督的算法(但我们的数据应该是离散的吧)
另一种OCSVNM(one class svm) 或者叫做SVDD，这同样是一种无监督的算法(应该吧)
https://blog.csdn.net/antkillerfarm/article/details/73457229
https://blog.csdn.net/bbbeoy/article/details/79159652
这个知乎的答案也很好：https://zhuanlan.zhihu.com/p/32784067
但考虑到我们也许会手动给数据进行标注，那么可以参考下面这篇博客，这个介绍的是一种引入负样本的有监督学习的SVDD：https://blog.csdn.net/sterben25/article/details/79106351
或者我们可以对数据做一些下采样或者过采样，来达到数据正负的平衡，然后采用一些传统的分类方法来进行分类，比如贝叶斯、逻辑回归、KNN等等，甚至可以用深度学习的方法进行分类，这里就不一一展开了
